-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL,
    user_name text NOT NULL,
    user_address text,
    password text NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.books
(
    book_id integer NOT NULL,
    name text NOT NULL,
    author text,
    "category " text,
    published_date date,
    language text NOT NULL,
    location text NOT NULL,
    page_amount integer,
    availability boolean NOT NULL,
    PRIMARY KEY (book_id)
);

CREATE TABLE IF NOT EXISTS public.book_info
(
    book_id integer NOT NULL,
    user_id integer NOT NULL,
    borrower_name text NOT NULL,
    borrow_date date NOT NULL,
    return_date date NOT NULL,
    PRIMARY KEY (book_id, borrower_id, user_id)
);

ALTER TABLE IF EXISTS public.book_info
    ADD FOREIGN KEY (book_id)
    REFERENCES public.books (book_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.book_info
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
