-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.users
(
    "userID" integer NOT NULL,
    "userName" text COLLATE pg_catalog."default" NOT NULL,
    "userAddress" text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY ("userID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.books
(
    "bookID" bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    author text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default" NOT NULL,
    "publishedYear" integer,
    language text COLLATE pg_catalog."default" NOT NULL,
    location text COLLATE pg_catalog."default" NOT NULL,
    "pageAmount" integer,
    availability boolean NOT NULL,
    CONSTRAINT books_pkey PRIMARY KEY ("bookID")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.books
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public."booksInfo"
(
    "bookID" bigint NOT NULL,
    "userID" integer NOT NULL,
    "borrowName" text COLLATE pg_catalog."default" NOT NULL,
    "borrowDate" date NOT NULL,
    "returnDate" date NOT NULL,
    CONSTRAINT "booksInfo_pkey" PRIMARY KEY ("bookID"),
    CONSTRAINT "booksInfo_bookID_fkey" FOREIGN KEY ("bookID")
        REFERENCES public.books ("bookID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "booksInfo_userID_fkey" FOREIGN KEY ("userID")
        REFERENCES public.users ("userID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."booksInfo"
    OWNER to postgres;


END;
